server:
  port: ${SERVER_PORT:8080}
  url: ${SERVER_URL:http://localhost:${SERVER_PORT:8080}}

spring:
  application:
    name: catsgram-auth-service

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: catsgram
            client-secret: lcftlbsJalSbJL5SSoK8KRo8Q5stYKg1
            client-name: catsgram
            authorization-grant-type: authorization_code
            scope: openid, profile, email
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:9091/realms/catsgram}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29098}

keycloak:
  url: ${SERVER_KEYCLOAK_URL:http://localhost:9091}
  admin-id: ${ADMIN_ID:admin-cli}
  admin-secret: ${ADMIN_SECRET:ykWJDl0tVHIboXXiuu0nRYfHkbpuij5H}
  realm: ${REALM:catsgram}

logging:
  level:
    ru.practicum.*: debug

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
