server:
  port: 8085

spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29098}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/catsgram-users}
    username: ${SPRING_DATASOURCE_USERNAME:mira}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  kafka:
    topics:
      user:
        registration: user-registration
        deleting: user-deleting

logging:
  level:
    ru.practicum.*: debug