server:
  port: 8085

spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29098}

app:
  kafka:
    topics:
      user:
        registration: user-registration
        deleting: user-deleting

logging:
  level:
    ru.practicum.*: debug