spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:test_db
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: none